In [1]:
import model.ab as ab
import model.detr as detr
import torch

In [2]:
a = ab.get_spatial_position_embedding(256, torch.randn(1, 3, 32, 32))
b = detr.get_spatial_position_embedding(256, torch.randn(1, 3, 32, 32))

torch.allclose(a, b, atol=1e-5)

tensor([[ 0.],
        [ 0.],
        [ 0.],
        ...,
        [31.],
        [31.],
        [31.]])


True

In [8]:
a.shape, b.shape

(torch.Size([1024, 256]), torch.Size([1024, 256]))

In [9]:
a

tensor([[ 0.0000,  0.0000,  0.0000,  ...,  1.0000,  1.0000,  1.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  1.0000,  1.0000,  1.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  1.0000,  1.0000,  1.0000],
        ...,
        [-0.4040, -0.9882, -0.3693,  ...,  1.0000,  1.0000,  1.0000],
        [-0.4040, -0.9882, -0.3693,  ...,  1.0000,  1.0000,  1.0000],
        [-0.4040, -0.9882, -0.3693,  ...,  1.0000,  1.0000,  1.0000]])

In [5]:
b

tensor([[ 0.0000,  0.0000,  0.0000,  ...,  1.0000,  1.0000,  1.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  1.0000,  1.0000,  1.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  1.0000,  1.0000,  1.0000],
        ...,
        [-0.4040,  0.9900, -0.9507,  ...,  1.0000,  1.0000,  1.0000],
        [-0.4040,  0.9900, -0.9507,  ...,  1.0000,  1.0000,  1.0000],
        [-0.4040,  0.9900, -0.9507,  ...,  1.0000,  1.0000,  1.0000]])