In [1]:
import model.ab as ab
import model.detr as detr
import torch

In [4]:
a = ab.get_spatial_position_embedding(256, torch.randn(1, 3, 32, 64))
b = detr.get_spatial_position_embedding(256, torch.randn(1, 3, 32, 32))

torch.allclose(a, b, atol=1e-5)

grid:  tensor([[ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  ...,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  ...,  2.,  2.,  2.],
        ...,
        [29., 29., 29.,  ..., 29., 29., 29.],
        [30., 30., 30.,  ..., 30., 30., 30.],
        [31., 31., 31.,  ..., 31., 31., 31.]])  grid[1]:  tensor([[ 0.,  1.,  2.,  ..., 61., 62., 63.],
        [ 0.,  1.,  2.,  ..., 61., 62., 63.],
        [ 0.,  1.,  2.,  ..., 61., 62., 63.],
        ...,
        [ 0.,  1.,  2.,  ..., 61., 62., 63.],
        [ 0.,  1.,  2.,  ..., 61., 62., 63.],
        [ 0.,  1.,  2.,  ..., 61., 62., 63.]])
tensor([[ 0.],
        [ 0.],
        [ 0.],
        ...,
        [31.],
        [31.],
        [31.]])


RuntimeError: The size of tensor a (2048) must match the size of tensor b (1024) at non-singleton dimension 0

In [8]:
a.shape, b.shape

(torch.Size([1024, 256]), torch.Size([1024, 256]))

In [9]:
a

tensor([[ 0.0000,  0.0000,  0.0000,  ...,  1.0000,  1.0000,  1.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  1.0000,  1.0000,  1.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  1.0000,  1.0000,  1.0000],
        ...,
        [-0.4040, -0.9882, -0.3693,  ...,  1.0000,  1.0000,  1.0000],
        [-0.4040, -0.9882, -0.3693,  ...,  1.0000,  1.0000,  1.0000],
        [-0.4040, -0.9882, -0.3693,  ...,  1.0000,  1.0000,  1.0000]])

In [5]:
b

tensor([[ 0.0000,  0.0000,  0.0000,  ...,  1.0000,  1.0000,  1.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  1.0000,  1.0000,  1.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  1.0000,  1.0000,  1.0000],
        ...,
        [-0.4040,  0.9900, -0.9507,  ...,  1.0000,  1.0000,  1.0000],
        [-0.4040,  0.9900, -0.9507,  ...,  1.0000,  1.0000,  1.0000],
        [-0.4040,  0.9900, -0.9507,  ...,  1.0000,  1.0000,  1.0000]])