In [1]:
import torch
import tensor
import numpy as np

In [2]:
X = np.random.randn(8, 16, 32)
X_tensor = tensor.Tensor.from_numpy(data=X, requires_grad=True)
X_torch = torch.from_numpy(X)
X_torch = X_torch.requires_grad_(True)
X_torch.is_leaf

y = X_tensor + 5
z = y + 10
m = z.mean()

In [3]:
m.backward()

In [4]:
y_torch = X_torch + 5
z_torch = y_torch + 10
m_torch = torch.mean(z_torch)
m_torch.backward()

In [5]:
print(X_torch.grad)

tensor([[[0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         ...,
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002]],

        [[0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         ...,
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002]],

        [[0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.

In [6]:
print(X_tensor.grad.data )

[[[0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  ...
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]]

 [[0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  ...
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]]

 [[0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.000244

In [7]:
np.allclose(X_tensor.grad.data, X_torch.grad.numpy())

True

In [8]:
X_np = np.random.randn(8, 16, 32)
Y_np = np.random.randn(32, 24)
X_tens = tensor.Tensor.from_numpy(X_np, requires_grad=True)
Y_tens = tensor.Tensor.from_numpy(Y_np, requires_grad=True)

X_torch = torch.from_numpy(X_np)
X_torch.requires_grad_(True)
Y_torch = torch.from_numpy(Y_np)
Y_torch.requires_grad_(True)

tensor([[-0.3925,  0.1433,  0.4466, -1.0877,  0.9150, -0.4496,  0.4410, -0.5206,
          1.3768,  1.1518, -1.4303, -0.1101, -0.3396,  0.2695,  0.3035, -0.3035,
         -0.2093, -1.8583,  1.7126,  0.4404, -0.5424, -0.6500,  1.8538,  0.0305],
        [-0.7895,  0.5414, -0.2046,  1.9671, -0.7366, -0.0654, -0.6106, -0.3564,
         -1.5053, -0.0112,  0.6707, -1.3382, -0.3212, -0.2658,  0.4753,  1.8678,
          1.5272,  0.5929,  0.6205, -0.2612,  1.0315,  2.1461, -0.0451, -0.9779],
        [-0.3927,  1.1502,  1.0552, -1.0117,  0.0507, -1.3117, -0.4030, -0.6845,
          1.5821,  0.0755,  0.0687,  0.1708, -2.2832, -0.8632, -1.3987,  0.5252,
          2.3077,  0.6774, -0.4420, -0.0261,  0.6449, -0.4377,  0.2400, -0.7486],
        [ 0.3625,  0.0865, -0.1146, -0.8207, -0.4271, -0.8294,  0.2604,  0.0506,
          0.7358, -1.4131,  0.6141,  0.0730, -0.2797,  1.5572, -0.1467, -1.0339,
         -2.1810, -1.3321,  1.7340,  0.5399, -0.4207, -1.0783, -0.1938,  1.3909],
        [-0.4188,  0.019

In [9]:
Z = X_tens.matmul(Y_tens)
W = Z.mean()
W.backward()

In [10]:
Z_torch = X_torch.matmul(Y_torch)
W_torch = Z_torch.mean()
W_torch.backward()

In [11]:
np.allclose(X_tens.grad.data, X_torch.grad.numpy()),np.allclose(Y_tens.grad.data, Y_torch.grad.numpy())

(True, True)

In [12]:
Y_torch.grad

tensor([[ 0.0070,  0.0070,  0.0070,  0.0070,  0.0070,  0.0070,  0.0070,  0.0070,
          0.0070,  0.0070,  0.0070,  0.0070,  0.0070,  0.0070,  0.0070,  0.0070,
          0.0070,  0.0070,  0.0070,  0.0070,  0.0070,  0.0070,  0.0070,  0.0070],
        [ 0.0026,  0.0026,  0.0026,  0.0026,  0.0026,  0.0026,  0.0026,  0.0026,
          0.0026,  0.0026,  0.0026,  0.0026,  0.0026,  0.0026,  0.0026,  0.0026,
          0.0026,  0.0026,  0.0026,  0.0026,  0.0026,  0.0026,  0.0026,  0.0026],
        [-0.0014, -0.0014, -0.0014, -0.0014, -0.0014, -0.0014, -0.0014, -0.0014,
         -0.0014, -0.0014, -0.0014, -0.0014, -0.0014, -0.0014, -0.0014, -0.0014,
         -0.0014, -0.0014, -0.0014, -0.0014, -0.0014, -0.0014, -0.0014, -0.0014],
        [-0.0011, -0.0011, -0.0011, -0.0011, -0.0011, -0.0011, -0.0011, -0.0011,
         -0.0011, -0.0011, -0.0011, -0.0011, -0.0011, -0.0011, -0.0011, -0.0011,
         -0.0011, -0.0011, -0.0011, -0.0011, -0.0011, -0.0011, -0.0011, -0.0011],
        [ 0.0035,  0.003

In [13]:
Y_tens.grad

{'data': array([[ 0.00702757,  0.00702757,  0.00702757,  0.00702757,  0.00702757,
         0.00702757,  0.00702757,  0.00702757,  0.00702757,  0.00702757,
         0.00702757,  0.00702757,  0.00702757,  0.00702757,  0.00702757,
         0.00702757,  0.00702757,  0.00702757,  0.00702757,  0.00702757,
         0.00702757,  0.00702757,  0.00702757,  0.00702757],
       [ 0.00257175,  0.00257175,  0.00257175,  0.00257175,  0.00257175,
         0.00257175,  0.00257175,  0.00257175,  0.00257175,  0.00257175,
         0.00257175,  0.00257175,  0.00257175,  0.00257175,  0.00257175,
         0.00257175,  0.00257175,  0.00257175,  0.00257175,  0.00257175,
         0.00257175,  0.00257175,  0.00257175,  0.00257175],
       [-0.00137766, -0.00137766, -0.00137766, -0.00137766, -0.00137766,
        -0.00137766, -0.00137766, -0.00137766, -0.00137766, -0.00137766,
        -0.00137766, -0.00137766, -0.00137766, -0.00137766, -0.00137766,
        -0.00137766, -0.00137766, -0.00137766, -0.00137766, -0.001