In [1]:
import torch
import tensor
import numpy as np

In [2]:
X = np.random.randn(8, 16, 32)
X_tensor = tensor.Tensor.from_numpy(data=X, requires_grad=True)
X_torch = torch.from_numpy(X)
X_torch = X_torch.requires_grad_(True)
X_torch.is_leaf

y = X_tensor + 5
z = y + 10
m = z.mean()

In [3]:
m.backward()

In [4]:
y_torch = X_torch + 5
z_torch = y_torch + 10
m_torch = torch.mean(z_torch)
m_torch.backward()

In [9]:
print(X_torch.grad)

tensor([[[0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         ...,
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002]],

        [[0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         ...,
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002]],

        [[0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.

In [10]:
print(X_tensor.grad.data )

[[[0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  ...
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]]

 [[0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  ...
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]]

 [[0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.000244

In [12]:
np.allclose(X_tensor.grad.data, X_torch.grad.numpy())

True