In [2]:
import torch
import tensor
import numpy as np

In [16]:
x = torch.randn((4, 2, 4, 2), requires_grad=True)
y = torch.randn((4, 2, 4, 2))

u = 2 * x
v = x + y
z = (u + v).mean()
z.backward()

In [18]:
x.grad.shape

torch.Size([4, 2, 4, 2])

In [15]:
A = np.array([[1, 1, 1], [2, 2, 2], [5, 5, 5]])
B = np.array([[0, 1, 0], [1, 1, 0], [1, 1, 1]])
np.einsum('ij,jk->i', A, B)

res = np.empty((3,))

for i in range(3):
    total = 0
    for j in range(3):
        for k in range(3):
            total += A[i, j] * B[j, k]
    res[i] = total
res,np.einsum('ij,jk->ik', A, B)



(array([ 6., 12., 30.]),
 array([[ 2,  3,  1],
        [ 4,  6,  2],
        [10, 15,  5]]))

In [6]:
yy, xx = np.mgrid[0:3, 0:3]

In [9]:
xx - 1

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [ ]:
torch.einsum('ii->i', torch.ones(3, 3))

out = np.empty((3, ))
for i in range(3):
    for j in range(3):
        out[i] += torch.ones(3, 3)[i, j]

out, torch.einsum('ii->i', torch.ones(3, 3))

(array([7., 7., 7.]), tensor([1., 1., 1.]))