In [1]:
import torch
import tensor
import numpy as np

In [2]:
X = np.random.randn(8, 16, 32)
X_tensor = tensor.Tensor.from_numpy(data=X, requires_grad=True)
X_torch = torch.from_numpy(X)
X_torch = X_torch.requires_grad_(True)
X_torch.is_leaf

y = X_tensor + 5
z = y + 10
m = z.mean()

In [3]:
m.backward()

In [4]:
y_torch = X_torch + 5
z_torch = y_torch + 10
m_torch = torch.mean(z_torch)
m_torch.backward()

In [9]:
print(X_torch.grad)

tensor([[[0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         ...,
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002]],

        [[0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         ...,
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002]],

        [[0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
         [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.

In [10]:
print(X_tensor.grad.data )

[[[0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  ...
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]]

 [[0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  ...
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]]

 [[0.00024414 0.00024414 0.00024414 ... 0.00024414 0.00024414 0.00024414]
  [0.00024414 0.000244

In [12]:
np.allclose(X_tensor.grad.data, X_torch.grad.numpy())

True

In [2]:
X_np = np.random.randn(8, 16, 32)
Y_np = np.random.randn(32, 24)
X_tens = tensor.Tensor.from_numpy(X_np, requires_grad=True)
Y_tens = tensor.Tensor.from_numpy(Y_np, requires_grad=True)

X_torch = torch.from_numpy(X_np)
X_torch.requires_grad_(True)
Y_torch = torch.from_numpy(Y_np)
Y_torch.requires_grad_(True)

tensor([[-1.6552e+00, -8.5823e-01, -3.1341e-01,  7.0823e-02,  4.9451e-01,
          1.2205e+00,  1.5783e-01, -2.0119e-01,  5.1081e-01, -8.5429e-01,
         -5.1826e-01, -1.5125e+00,  1.7728e+00,  1.2324e-01, -6.0253e-01,
         -7.8635e-01,  8.0832e-01, -1.1714e+00,  7.1308e-01,  6.1369e-01,
          9.2918e-01,  4.3652e-01,  7.5832e-01, -1.0868e+00],
        [ 3.1966e-01, -1.4226e+00, -1.5246e-01, -3.0362e-01, -1.9037e+00,
         -2.6597e-01,  2.5288e-01,  1.0504e+00, -1.9355e+00,  2.6489e-01,
         -1.2996e+00, -8.3880e-02,  6.6351e-01, -5.5736e-01, -8.9531e-01,
         -8.3134e-02, -6.2909e-01, -9.3047e-01, -5.2402e-01, -1.4313e+00,
         -1.2999e+00, -9.9132e-02,  5.3460e-01,  1.1490e+00],
        [-1.1438e+00, -5.4094e-01,  3.3456e-02, -6.2016e-01,  1.2649e+00,
          1.9349e+00, -1.2571e-01, -5.6274e-01,  1.6537e+00, -5.2859e-01,
          2.6117e-01, -4.1023e-01, -1.4356e+00,  1.4980e+00,  1.5782e+00,
          1.5267e-01,  1.4991e+00, -1.6605e-01, -6.2286e-01, -

In [3]:
Z = X_tens.matmul(Y_tens)
W = Z.mean()
W.backward()

In [4]:
Z_torch = X_torch.matmul(Y_torch)
W_torch = Z_torch.mean()
W_torch.backward()

In [9]:
np.allclose(X_tens.grad.data, X_torch.grad.numpy()),np.allclose(Y_tens.grad.data, Y_torch.grad.numpy())

(True, True)

In [6]:
Y_torch.grad

tensor([[ 0.0048,  0.0048,  0.0048,  0.0048,  0.0048,  0.0048,  0.0048,  0.0048,
          0.0048,  0.0048,  0.0048,  0.0048,  0.0048,  0.0048,  0.0048,  0.0048,
          0.0048,  0.0048,  0.0048,  0.0048,  0.0048,  0.0048,  0.0048,  0.0048],
        [-0.0047, -0.0047, -0.0047, -0.0047, -0.0047, -0.0047, -0.0047, -0.0047,
         -0.0047, -0.0047, -0.0047, -0.0047, -0.0047, -0.0047, -0.0047, -0.0047,
         -0.0047, -0.0047, -0.0047, -0.0047, -0.0047, -0.0047, -0.0047, -0.0047],
        [-0.0021, -0.0021, -0.0021, -0.0021, -0.0021, -0.0021, -0.0021, -0.0021,
         -0.0021, -0.0021, -0.0021, -0.0021, -0.0021, -0.0021, -0.0021, -0.0021,
         -0.0021, -0.0021, -0.0021, -0.0021, -0.0021, -0.0021, -0.0021, -0.0021],
        [-0.0015, -0.0015, -0.0015, -0.0015, -0.0015, -0.0015, -0.0015, -0.0015,
         -0.0015, -0.0015, -0.0015, -0.0015, -0.0015, -0.0015, -0.0015, -0.0015,
         -0.0015, -0.0015, -0.0015, -0.0015, -0.0015, -0.0015, -0.0015, -0.0015],
        [-0.0029, -0.002

In [7]:
Y_tens.grad

{'data': array([[ 0.00483474,  0.00483474,  0.00483474,  0.00483474,  0.00483474,
         0.00483474,  0.00483474,  0.00483474,  0.00483474,  0.00483474,
         0.00483474,  0.00483474,  0.00483474,  0.00483474,  0.00483474,
         0.00483474,  0.00483474,  0.00483474,  0.00483474,  0.00483474,
         0.00483474,  0.00483474,  0.00483474,  0.00483474],
       [-0.00472725, -0.00472725, -0.00472725, -0.00472725, -0.00472725,
        -0.00472725, -0.00472725, -0.00472725, -0.00472725, -0.00472725,
        -0.00472725, -0.00472725, -0.00472725, -0.00472725, -0.00472725,
        -0.00472725, -0.00472725, -0.00472725, -0.00472725, -0.00472725,
        -0.00472725, -0.00472725, -0.00472725, -0.00472725],
       [-0.00207338, -0.00207338, -0.00207338, -0.00207338, -0.00207338,
        -0.00207338, -0.00207338, -0.00207338, -0.00207338, -0.00207338,
        -0.00207338, -0.00207338, -0.00207338, -0.00207338, -0.00207338,
        -0.00207338, -0.00207338, -0.00207338, -0.00207338, -0.002